services:
  core_redis:
    container_name: redis
    image: redis:7.2.1-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - django_redis:/data
    networks:
      - fatmug_network
    restart: always

  core_psql:
    container_name: ${POSTGRES_DB}
    image: postgres:16.0-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - django_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    networks:
      - fatmug_network
    restart: always

  core_dj:
    container_name: core
    image: core_dj:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEBUG: ${DEBUG}
        CI_JOB_TOKEN: ${CI_JOB_TOKEN}
        GITLAB_PRIVATE_ACCESS_TOKEN: ${GITLAB_PRIVATE_ACCESS_TOKEN}
        REGISTRY: >
          ${CI_API_V4_URL}/projects/7/packages/generic/ci-uploaded-packages/0.1/pip_api_gateway.tar.gz,
          ${CI_API_V4_URL}/projects/15/packages/generic/ci-uploaded-packages/0.1/pip_custom_package.tar.gz,
          ${CI_API_V4_URL}/projects/25/packages/generic/ci-uploaded-packages/0.1/pip_kn_pkg.tar.gz,
        SSH_KEY_PATH: ${SSH_KEY_PATH}
        IS_IN_PRODUCTION: ${IS_IN_PRODUCTION}
    volumes:
      - .:/app
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
      - ${PLAYGROUND_PORT}:${PLAYGROUND_PORT}
    env_file: .env
    networks:
      - fatmug_network
    depends_on:
      - core_psql
    restart: always

  core_celery:
    container_name: celery
    image: core_dj:latest
    command: python manage.py celery
    volumes:
      - .:/app
    env_file: .env
    networks:
      - fatmug_network
    depends_on:
      - core_dj
      - core_redis
    restart: always

networks:
  fatmug_network:
    external: true

volumes:
  django_db:
  django_redis:
